name = "workers-site"
account_id = ""
type = "webpack"
workers_dev = true
webpack_config = "workers-site/webpack.development.js"

[site]
bucket = "./deploy"
entry-point = "workers-site"

[env.production]
vars = { ENVIRONMENT = "production" }
zone_id = ""
route = "*xedit.app/*"
webpack_config = "workers-site/webpack.production.js"